### ISSUE TITLE
[BUG] waypaper engine stopped working and can not be installed

### ISSUE THREAD

**Issue by sabbateus** [0bCdian/Waypaper-Engine#73]
Tried to use the git version. Still not working.

Here is the full log.
[log.txt](https://github.com/user-attachments/files/17787781/log.txt)

**Comment by 0bCdian** [comment]
Hi, sorry for the late reply, I haven't been very active with this project lately due to other personal commitments, I'll check the problem out and fix it asap.

**Comment by 0bCdian** [comment]
Upon further inspecting the logs you sent, I see you're using node 23.2.0, the problem was a dependency not working on your node version, I pushed some changes on git. Try those and see if it's fixed.

**Comment by sabbateus** [comment]
Ok, still getting weird errors, but nvm. 
[log.txt](https://github.com/user-attachments/files/17815577/log.txt)

Huge respect to you for creating this!

**Comment by 0bCdian** [comment]
Did you try clean installing? If you're using yay first do a yay -Rns waypaper-engine-git and then reinstall , when prompted to clean build press Y, I tested building on your node version 23.2.0) and it worked no problems. See if that helps. If not I'll keep looking.

**Comment by sabbateus** [comment]
Nope, even with a cleanBuild.
[log.txt](https://github.com/user-attachments/files/17832788/log.txt)

**Comment by 0bCdian** [comment]
can you send me a list with the installed packages in your system? do a `yay -Q `  to see if there's something funky going on. I am not sure why is not building for you but I'm certain that it most probably is a bug in your system rather than the application code itself, because I have some workflows on github actions that build the app on different node versions before merging and I just added a new one for node 23x and it did build successfully, so chances are something is wrong in your system.

**Comment by sabbateus** [comment]
sure, here it is.
[pkg-list.txt](https://github.com/user-attachments/files/17850976/pkg-list.txt)

It is worth noting that I am using cachy-os and chaotic-aur repos, maybe the issue might be with them, I don't know. Never had such problem before.

**Comment by 0bCdian** [comment]
Mmm, I may be grasping straws here, but I see you have a globally installed instance of node-gyp and libvips in your system, and for sharp uses those packages to rebuild the binary it downloads. In the logs it says that it's trying to use those local versions instead of the ones downloaded from the package json. See if those packages are required by other apps in your system, if not. Delete them and try again.

`pacman -Qi libvips | grep "Required By"`
``pacman -Qi node-gyp | grep "Required By"``

**Comment by sabbateus** [comment]
libvips is not required, so I safely deleted it. Did resolve the problem? Kinda... The package is building for more than 5 minutes without any workload on my CPU, which is strange. Usually it ends in 15-30 seconds.
node-gyp is required by npm (ships as a dependency in extra repo) and pnpm. So I technically can't delete.

**Comment by sabbateus** [comment]
Yep, now it finished with no errors. Thank you for your help! :)
libvips was the source of issues.
